name: test

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: test
        run: |
          make
          make test
